### ISSUE TITLE
Cant find namespaces

### ISSUE THREAD

**Issue by justinLifelike** [GimChuang/UnityPhotoBooth#1]
Hi GimCHuang, 

I downloaded this project to test it out, 
But I get all these namespace errors. 
It cant seem to find all these webcamtools, phototools, webtools? 
How can I fix this? 

Thanks in advance! 

![image](https://user-images.githubusercontent.com/89152236/223749543-bf7af151-ddf3-414e-81b9-daae1bdcbe60.png)
![image](https://user-images.githubusercontent.com/89152236/223749594-e7941dee-4f66-4f87-9751-7464f637768c.png)

**Comment by GimChuang** [comment]
Hello justinLifeLike,
Could you try to [use](https://github.com/GimChuang/UnityPhotoBooth#notes) `git clone --recurse-submodules https://github.com/GimChuang/UnityPhotoBooth.git`?
Webcamtools, phototools, and webtools are git submodules, so they won't be downloaded when you download the project with the download zip button.
